name: Rick and Morty API CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -t rick-and-morty-api .
    
    - name: Run Docker container
      run: docker run -d -p 8080:8080 rick-and-morty-api
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/bin/minikube
    
    - name: Start minikube
      run: minikube start --driver=docker
    
    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.9.0'
    
    - name: Deploy to minikube
      run: |
        eval $(minikube docker-env)
        docker build -t rick-and-morty-api .
        helm install rick-and-morty-api ./helm --debug
        
    - name: Wait for deployment
      run: |
        echo "Waiting for deployment to be ready..."
        kubectl wait --for=condition=available --timeout=300s deployment/rick-and-morty-api
        
    - name: View application logs
      run: |
        echo "Application logs:"
        kubectl logs -l app=rick-and-morty-api --tail=100
        
    - name: Port forward and run tests
      run: |
        kubectl port-forward service/rick-and-morty-api-service 8080:80 &
        sleep 10
        curl -v http://localhost:8080/healthcheck
        curl -v http://localhost:8080/characters
        kill %1

    - name: Clean up
      if: always()
      run: minikube delete
