name: Rick and Morty API CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -t rick-and-morty-api .
    
    - name: Run Docker container
      run: docker run -d -p 8080:8080 rick-and-morty-api
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
    
    - name: Start minikube
      run: minikube start --driver=docker
    
    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.9.0'
    
    - name: Debug - List Helm chart contents
      run: |
        ls -R ./helm
        cat ./helm/Chart.yaml
        cat ./helm/values.yaml
        cat ./helm/templates/deployment.yaml
    
    - name: Deploy to minikube
      run: |
        eval $(minikube docker-env)
        docker build -t rick-and-morty-api .
        helm install rick-and-morty-api ./helm --debug
        
    - name: Debug - Check Helm release
      run: |
        helm list
        helm get all rick-and-morty-api
        
    - name: Debug - Check Kubernetes resources
      run: |
        kubectl get all
        kubectl describe deployments
        kubectl describe pods
        
    - name: Wait for deployment
      run: |
        echo "Waiting for deployment to be ready..."
        kubectl wait --for=condition=available --timeout=300s deployment/rick-and-morty-api
        echo "Deployment is ready"
        
    - name: Get service URL
      run: |
        minikube service list
        minikube service rick-and-morty-api --url
        
    - name: Run API tests
      run: |
        SERVICE_URL=$(minikube service rick-and-morty-api --url)
        echo "Service URL: $SERVICE_URL"
        curl -v $SERVICE_URL/healthcheck
        curl -v $SERVICE_URL/characters

    - name: Clean up
      if: always()
      run: minikube delete
