name: Rick and Morty API CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -t rick-and-morty-api .
    
    - name: Run Docker container
      run: docker run -d -p 8080:8080 rick-and-morty-api
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
    
    - name: Start minikube
      run: minikube start --driver=docker
    
    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.9.0'
    
    - name: Debug - Display Helm chart files
      run: |
        echo "Contents of Chart.yaml:"
        cat helm/Chart.yaml
        echo "Contents of values.yaml:"
        cat helm/values.yaml
        echo "Contents of templates/Deployment.yaml:"
        cat helm/templates/Deployment.yaml
        echo "Contents of templates/Service.yaml:"
        cat helm/templates/Service.yaml
        echo "Contents of templates/Ingress.yaml:"
        cat helm/templates/Ingress.yaml
    
    - name: Validate Helm chart
      run: helm lint ./helm
    
    - name: Debug - Helm template
      run: helm template ./helm
    
    - name: Deploy to minikube
      run: |
        eval $(minikube docker-env)
        docker build -t rick-and-morty-api .
        helm install rick-and-morty-api ./helm --debug
        
    - name: Debug - Check Helm release
      run: |
        helm list
        helm get all rick-and-morty-api
        
    - name: Debug - Check Kubernetes resources
      run: |
        echo "All resources:"
        kubectl get all
        echo "Deployments:"
        kubectl get deployments
        echo "Services:"
        kubectl get services
        echo "Pods:"
        kubectl get pods
        
    - name: Wait for deployment
      run: |
        echo "Waiting for deployment to be ready..."
        kubectl wait --for=condition=available --timeout=300s deployment/rick-and-morty-api
        
    - name: Get service URL
      run: |
        echo "All services:"
        minikube service list
        echo "Attempting to get rick-and-morty-api-service URL:"
        minikube service rick-and-morty-api-service --url

    - name: Run API tests
      run: |
        SERVICE_URL=$(minikube service rick-and-morty-api-service --url)
        echo "Service URL: $SERVICE_URL"
        curl -v $SERVICE_URL/healthcheck || echo "Failed to reach /healthcheck endpoint"
        curl -v $SERVICE_URL/characters || echo "Failed to reach /characters endpoint"

    - name: Clean up
      if: always()
      run: minikube delete
