name: Rick and Morty API CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -t rick-and-morty-api .
    
    - name: Run Docker container
      run: docker run -d -p 8080:8080 rick-and-morty-api
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
    
    - name: Start minikube
      run: minikube start --driver=docker
    
    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.9.0'
    
    - name: Deploy to minikube
      run: |
        eval $(minikube docker-env)
        docker build -t rick-and-morty-api .
        helm install rick-and-morty-api ./helm
        
    - name: Wait for deployment
      run: |
        echo "Waiting for deployment to be ready..."
        kubectl wait --for=condition=available --timeout=300s deployment/rick-and-morty-api-deployment
        echo "Deployment is ready"
        
    - name: Debug - Check pod status
      run: |
        kubectl get pods
        kubectl describe pods
        
    - name: Get service URL
      run: |
        minikube service list
        minikube service rick-and-morty-api-service --url
        
    - name: Run API tests
      run: |
        SERVICE_URL=$(minikube service rick-and-morty-api-service --url)
        echo "Service URL: $SERVICE_URL"
        curl -v $SERVICE_URL/healthcheck
        curl -v $SERVICE_URL/characters

    - name: Clean up
      if: always()
      run: minikube delete
